### ISSUE TITLE
每日抽卡有问题

### ISSUE THREAD

**Issue by jiaoxiaohang** [moonheart/mementomori-helper#1]
每日免费/金币抽卡功能使用显示 用了我30张白金兑换卷,然后报错停止操作

**Comment by jiaoxiaohang** [comment]
还有祈愿之泉的游击任务不能领取奖励

**Comment by moonheart** [comment]
还记得报的是什么错吗，账号里面还有哪些可以抽卡的资源？

**Comment by jiaoxiaohang** [comment]
抽卡报错:
System.InvalidOperationException: PresentReceiveOverLimitCountPresent at MementoMori.MementoMoriFuncs.GetResponse[TReq,TResp](TReq req) in D:\Downloads\mementomori-helper-master\MementoMori\MementoMoriFuncs.cs:line 762 at MementoMori.MementoMoriFuncs.<PresentReceiveItem>b__87_0(Action`1 log, CancellationToken token) in D:\Downloads\mementomori-helper-master\MementoMori\MementoMoriFuncs.Ops.cs:line 230 at MementoMori.MementoMoriFuncs.<ExecuteQuickAction>b__81_0() in D:\Downloads\mementomori-helper-master\MementoMori\MementoMoriFuncs.Ops.cs:line 123
PresentReceiveOverLimitCountPresent
https://prd1-ap2-api.mememori-boi.com/api/present/receiveItem

抽卡资源有(我有的):白金召唤卷,友情点,属性召唤卷

而且武具的金币抽卡和免费抽卡没有完成

**Comment by moonheart** [comment]
PresentReceiveOverLimitCountPresent 这看起来是礼物箱满了，可以尝试领取礼物箱。如果领取礼物箱报错，可能是礼物箱没有可领取的内容或者是储物箱的某个物品数量上限达到了

**Comment by jiaoxiaohang** [comment]
> 
是因为用了30张白金召唤卷导致角色数量上限,所以有两个角色在礼物箱.(如果角色没到上限,会一直使用白金召唤卷吧0.0)

**Comment by moonheart** [comment]
是的，目前是会抽的卡有 金币，白金券，命运券，免费；会抽完所有可以抽的资源。属性券不会抽，因为每天的属性不一样

**Comment by jiaoxiaohang** [comment]
改成只抽金币和免费的比较好吧,万一现在的限定角色以后会进常驻池呢_(:з)∠)_

**Comment by moonheart** [comment]
关于自动抽卡的范围，后面可以加上设置，自行选择需要使用的抽卡类别

**Comment by jiaoxiaohang** [comment]
> 关于自动抽卡的范围，后面可以加上设置，自行选择需要使用的抽卡类别

嗯,加油(ง •_•)ง

**Comment by jiaoxiaohang** [comment]
我点击一键执行所有,最后在时空洞窟报错(虽然一键操作里没显示有时空洞窟功能)
报错信息:
System.InvalidOperationException: DungeonBattleNotBattleGrid at MementoMori.MementoMoriFuncs.GetResponse[TReq,TResp](TReq req) in D:\Downloads\mementomori-helper-master\MementoMori\MementoMoriFuncs.cs:line 762 at MementoMori.MementoMoriFuncs.<>c__DisplayClass46_0.<<AutoDungeonBattle>g__DoBattle|6>d.MoveNext() in D:\Downloads\mementomori-helper-master\MementoMori\MementoMoriFuncs.cs:line 482 --- End of stack trace from previous location --- at MementoMori.MementoMoriFuncs.AutoDungeonBattle(Action`1 log) in D:\Downloads\mementomori-helper-master\MementoMori\MementoMoriFuncs.cs:line 596 at MementoMori.MementoMoriFuncs.<AutoDungeonBattle>b__95_0(Action`1 log, CancellationToken token) in D:\Downloads\mementomori-helper-master\MementoMori\MementoMoriFuncs.Ops.cs:line 382 at MementoMori.MementoMoriFuncs.<ExecuteQuickAction>b__81_0() in D:\Downloads\mementomori-helper-master\MementoMori\MementoMoriFuncs.Ops.cs:line 123
DungeonBattleNotBattleGrid
https://prd1-ap2-api.mememori-boi.com/api/dungeonBattle/execBattle
当前第 1层，坐标 1,1，状态 Selected, 通常バトル BattleNormal 敌人战斗力 4631494
当前第 1层，坐标 0,0，状态 Done, 初期地点 Start 敌人战斗力 0

还有一个是祈愿之泉派遣,有一个没有派遣,我上线领了游击任务的奖励,再打开网页派遣就派遣成功了

**Comment by moonheart** [comment]
派遣目前算法还不完善，有可能某个任务派遣不成功；时空洞窟是包含在一键执行所有的功能里的，这个报错看情况是不应该的，需要进游戏看看当前所在节点的状态。

**Comment by jiaoxiaohang** [comment]
> 派遣目前算法还不完善，有可能某个任务派遣不成功；时空洞窟是包含在一键执行所有的功能里的，这个报错看情况是不应该的，需要进游戏看看当前所在节点的状态。

进游戏看和"当前第 1层，坐标 1,1，状态 Selected, 通常バトル BattleNormal 敌人战斗力 4631494"报的信息一样
![image](https://github.com/moonheart/mementomori-helper/assets/69664925/f453511c-533c-464a-af16-bd8aaa4160eb)
![image](https://github.com/moonheart/mementomori-helper/assets/69664925/050a520f-1999-486b-a7aa-d2c79f00c2d3)

**Comment by moonheart** [comment]
下载最新代码, 我增加了更多日志, 看看时空洞窟执行失败的详细请求信息, 如果信息包含 guid/playerid 之类的,可以模糊掉

**Comment by jiaoxiaohang** [comment]
System.InvalidOperationException: 非戰鬥石台。 at MementoMori.MementoMoriFuncs.GetResponse[TReq,TResp](TReq req) in D:\Downloads\2mementomori-helper-master\MementoMori\MementoMoriFuncs.cs:line 782 at MementoMori.MementoMoriFuncs.<>c__DisplayClass47_0.<<AutoDungeonBattle>g__DoBattle|6>d.MoveNext() in D:\Downloads\2mementomori-helper-master\MementoMori\MementoMoriFuncs.cs:line 507 --- End of stack trace from previous location --- at MementoMori.MementoMoriFuncs.AutoDungeonBattle(Action`1 log) in D:\Downloads\2mementomori-helper-master\MementoMori\MementoMoriFuncs.cs:line 621 at MementoMori.MementoMoriFuncs.<AutoDungeonBattle>b__96_0(Action`1 log, CancellationToken token) in D:\Downloads\2mementomori-helper-master\MementoMori\MementoMoriFuncs.Ops.cs:line 384 at MementoMori.MementoMoriFuncs.<ExecuteQuickAction>b__82_0() in D:\Downloads\2mementomori-helper-master\MementoMori\MementoMoriFuncs.Ops.cs:line 125
{"ErrorCode":122045,"Message":"","ErrorHandlingType":0,"ErrorMessageId":0,"MessageParams":null}

{"CharacterGuids":["*******","******","******",null,null],"DungeonGridGuid":"******","CurrentTermId":39}

非戰鬥石台。
https://prd1-ap2-api.mememori-boi.com/api/dungeonBattle/execBattle
当前第 1层，坐标 1,1，状态 Selected, 通常バトル BattleNormal 敌人战斗力 4631494

**Comment by jiaoxiaohang** [comment]
我下载code启动后网页报错:
An unhandled exception occurred while processing the request.
DirectoryNotFoundException: Could not find a part of the path 'D:\Downloads\3mementomori-helper-master\MementoMori.WebUI\Master\CharacterProfileMB'.
Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(string fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
红色部分:
MementoMori.Ortega.Share.Master.Table.TableBase<TM>.Load() in TableBase.cs
31.using (var fileStream = new FileStream(filePath, FileMode.Open, FileAccess.Read))
MementoMori.Ortega.Share.Masters.LoadAllMasters() in Masters.cs
150. if (!allTable.Load())
MementoMori.MementoMoriFuncs.DownloadMasterCatalog(bool useLocal) in MementoMoriFuncs.cs
174.Masters.LoadAllMasters();
MementoMori.MementoMoriFuncs..ctor(IOptions<AuthOption> authOption, IOptions<GameConfig> gameConfig) in MementoMoriFuncs.cs
108.DownloadMasterCatalog(true).ConfigureAwait(false).GetAwaiter().GetResult();
MementoMori.WebUI.Pages.Pages__Host.ExecuteAsync() in _Host.cshtml
8.<component type="typeof(App)" render-mode="ServerPrerendered"/>

我把上个版本的Master文件放进去后启动可以进入网页,但点角色会出现:
An unhandled exception has occurred. See browser dev tools for details. Reload
刷新后:
0.0.0.0:5290/Character
An unhandled exception occurred while processing the request.
ArgumentNullException: Value cannot be null. (Parameter 'collection')
System.Collections.Generic.List<T>.InsertRange(int index, IEnumerable<T> collection)
ArgumentNullException: Value cannot be null. (Parameter 'collection')
红色部分:
MementoMori.Ortega.Share.Data.Character.CharacterCollectionParameterInfo.Setup(List<UserCharacterCollectionDtoInfo> userCharacterCollectionDtoInfos) in CharacterCollectionParameterInfo.cs
65.baseParameterChangeInfos.AddRange(characterCollectionLevelMb.BaseParameterChangeInfos);
MementoMori.Ortega.Share.Extensions.BattleParameterExtension.CalcCharacterCollectionParameterInfo(List<UserCharacterCollectionDtoInfo> userCharacterCollectionDtoInfos) in BattleParameterExtension.cs
193.characterCollectionParameterInfo.Setup(userCharacterCollectionDtoInfos);
MementoMori.Ortega.Common.Utils.BattlePowerCalculatorUtil.CalcCharacterBattleParameter(UserCharacterInfo userCharacterInfo, LockEquipmentDeckType lockEquipmentDeckType) in BattlePowerCalculatorUtil.cs
153.var characterCollectionParameterInfo = characterCollectionDtoInfos.CalcCharacterCollectionParameterInfo();
MementoMori.Ortega.Common.Utils.BattlePowerCalculatorUtil.CalcCharacterBattleParameter(string userCharacterGuid, LockEquipmentDeckType lockEquipmentDeckType) in BattlePowerCalculatorUtil.cs
144.return CalcCharacterBattleParameter(userCharacterDtoInfo, lockEquipmentDeckType);
MementoMori.WebUI.Pages.Character.SelectCharacter(UserCharacterDtoInfo info) in Character.razor
125.var parameter = BattlePowerCalculatorUtil.CalcCharacterBattleParameter(info.Guid);
MementoMori.WebUI.Pages.Character.OnInitializedAsync() in Character.razor
119.SelectCharacter(_userSyncData.UserCharacterDtoInfos.MaxBy(d=>d.Level));
MementoMori.WebUI.Pages.Pages__Host.ExecuteAsync() in _Host.cshtml
8.<component type="typeof(App)" render-mode="ServerPrerendered"/>

**Comment by jiaoxiaohang** [comment]
时空洞窟的问题,
![image](https://github.com/moonheart/mementomori-helper/assets/69664925/78bc2098-ca83-46be-b7e1-e439c9e9d5d8)
我上游戏把队伍五人上齐,打开网页后自动时空洞窟功能能正常使用了

**Comment by moonheart** [comment]
好的, 那我大概知道是什么问题呢
