### ISSUE TITLE
请教下，我尝试通过浏览器登录账号并获取信息（类似MMTICU的功能）,loginPlayer总是不成功

### ISSUE THREAD

**Issue by rainsillwood** [moonheart/mementomori-helper#105]
前面getDataUri、createUser、setUserSetting、createWorldPlayer，都成功获取到信息了，但是在,loginPlayer这一步总是返回错误1：伺服器發生錯誤。请问有什么额外验证吗，我看返回的MagicOnionHost和MagicOnionPort没有用上，但是小助手也没有onion连接，还是说请求头不能有多余的信息？

**Comment by PackageInstaller** [comment]
@rainsillwood

**Comment by moonheart** [comment]
MagicOnion 是做实时通信的, 神殿会用到.

loginPlayer 失败的话, 发一下具体信息

**Comment by rainsillwood** [comment]
我是使用的TemperMonkey作为载体直接注入到MMTICU网站中，使用了插件自带的跨域请求，但是尝试利用iframe传递请求时候也是同样的情况，loginPlayer这一步报错。
项目地址：rainsillwood/MementoMoriGuildHelper
其中AdverisementId每次登录时使用了crypto.randomUUID()生成，ortegauuid也是crypto随机生成，去掉了字符'-'，这两个在一次会话内不会更改（使用getDataUri尝试版本时候会随机生成，但是成功后会固定）
所有的二进制数据请求体和响应体都使用msgpack-lite进行编解码
登录流程为：
1.getAuthToken：，请求地址为https://list.moonheart.dev/d/public/mmtm/AddressableLocalAssets/ScriptableObjects/AuthToken/AuthTokenData.json?v=' + Date.now()
2.getapkVersion和getDataUri：请求https://mememori-game.com/apps/vars.js获得App版本，在此基础上递增尝试请求https://prd1-auth.mememori-boi.com/api/auth/getDataUri，直到获取到正确的版本，这一步没问题
3.createUser
4.setUserSetting
5.createWorldPlayer，以上几步都没问题，这一步返回的响应头为
`HTTP/2 200
date: Sat, 14 Dec 2024 06:21:01 GMT
content-type: application/octet-stream
server: Kestrel
ortegastatuscode: 0
orteganextaccesstoken: 550fb51dfba049a4b9d38b9bf8b60999
ortegaassetversion: 275099d6699b05dff55f3d6370e5958ad78d1a03
ortegamasterversion: 1734074260011
ortegautcnowtimestamp: 1734157261623
`
响应体返回正常
5.loginPlayer，请求地址根据上一步获得的地址变为https://prd1-ap2-api.mememori-boi.com/api/user/loginPlayer
请求头为
`POST /api/user/loginPlayer HTTP/2
host: prd1-ap2-api.mememori-boi.com
user-agent: BestHTTP/2 v2.3.0
accept: */*
accept-language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
accept-encoding: gzip
ortegaaccesstoken: 550fb51dfba049a4b9d38b9bf8b60999
ortegadevicetype: 2
content-type: application/json; charset=UTF-8
ortegaappversion: 3.4.0
ortegauuid: b90d0173fc5c4efbaba20c21d5929a44
content-length: 93
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin
te: trailers
`
请求体内信息均为上一步所返回的信息
`
{
  "Password": "11478a12cd294c049aacace632f2b390",
  "PlayerId": 518127162019,
  "ErrorLogInfoList": null,
  "SteamTicket": null
}
`
响应头为
`
HTTP/2 200
date: Sat, 14 Dec 2024 06:21:02 GMT
content-type: application/octet-stream
server: Kestrel
ortegastatuscode: 1
orteganextaccesstoken: 
ortegaassetversion: 
ortegamasterversion: 1734074260011
ortegautcnowtimestamp: 1734157262592
`
响应体为，ErrorCode1对应的报错即为'伺服器發生錯誤'
`
{
  "ErrorCode": 1,
  "Message": "",
  "ErrorHandlingType": 0,
  "ErrorMessageId": 0,
  "MessageParams": null
}
`
除了创建新玩家，使用引继码登录也抱报同样的错误，只是提前到getComebackUserData这一步

**Comment by moonheart** [comment]
![image](https://github.com/user-attachments/assets/9dc05ee8-36ca-49ad-a558-7258f0cdff22)
我这用你的脚本请求时, body的内容不对,是哪里有问题吗?版本 Tampermonkey v5.3.3

正确的应该是下面
![image](https://github.com/user-attachments/assets/6f15e1df-6000-4575-9d42-0095a37965d0)

**Comment by rainsillwood** [comment]
看着像没经过msgpack处理，在932行的判断上option.msgpack判断成了false，但是我这边是正常的
option.msgpack是在buildOption这个函数初始化的，应该默认是true啊
![图片](https://github.com/user-attachments/assets/7408e9bb-3aac-4046-b9f6-f2552fc0ec2c)

**Comment by moonheart** [comment]
<img width="808" alt="image_83" src="https://github.com/user-attachments/assets/2d1ff5ed-410b-4d6c-9a82-0e6b3ea20e5e" />
我试了下 edge 和 chrome,都是这样, 这里显示的是正确的,但抓包出来是错误的,你的版本是多少

**Comment by rainsillwood** [comment]
我是Firefox133+tampermonkey5.3.2，我试了下chrome确实有这个问题，回退到5.3.2也会发生，应该是浏览器行为，搜了下其他人也没出现这情况，怪了

**Comment by moonheart** [comment]
我对比了下, 通过你的脚本发送的msgpack内容和我的代码发送的内容不太一样,不知道是不是这个原因

你的: playerId 类型为 float64
![image](https://github.com/user-attachments/assets/e48a4008-80a9-4bc0-9d81-ec6c30af668a)

我的: playerId 类型为 uint64
![image](https://github.com/user-attachments/assets/77b06336-3c9a-4760-9a6a-777a9f57928e)

不确定这个是否有影响

**Comment by rainsillwood** [comment]
！懂了是js坑爹的弱类型，数字位数太长被自动判定成float了
感谢，用msgpacklite附带的uint64库解决了！
