### ISSUE TITLE
一键操作不会打竞技场

### ISSUE THREAD

**Issue by jiaoxiaohang** [moonheart/mementomori-helper#13]
代码我只改了最后三行,但应该没涉及竞技场
![image](https://github.com/moonheart/mementomori-helper/assets/69664925/fa498094-03b0-4125-93e3-57f45424c503)

**Comment by moonheart** [comment]
autopvp 是自动竞技场，我看你这里好像把删掉了

**Comment by jiaoxiaohang** [comment]
> autopvp 是自动竞技场，是在单独的 job 里调用的

就是现在自动竞技场不放在一键操作了吗_(:з)∠)_

**Comment by moonheart** [comment]
没有放在执行全部的里面，但是可以单独点击竞技场的按钮

**Comment by jiaoxiaohang** [comment]
> 没有放在执行全部的里面，但是可以单独点击竞技场的按钮

那我自己放进去,,ԾㅂԾ,,
