### ISSUE TITLE
error when sending fountain teams

### ISSUE THREAD

**Issue by SolovastruAndrei** [moonheart/mementomori-helper#26]
I get this error on multiple accounts that I play....need to log in into the game and send them manually...maybe add something like "click on dispatch all" if this error occurs

![image](https://github.com/moonheart/mementomori-helper/assets/91962171/41bd3bd0-84f5-4764-8bd5-bd3c0bcf73ab)

![image](https://github.com/moonheart/mementomori-helper/assets/91962171/aab9c3dc-0cee-427d-8dc7-c5a32dc381b9)

**Comment by moonheart** [comment]
This is a known issue and is currently under investigation.

**Comment by moonheart** [comment]
Should be fixed in https://github.com/moonheart/mementomori-helper/releases/tag/v1.6.7
