### ISSUE TITLE
装备打磨打到目标值以上不会停

### ISSUE THREAD

**Issue by jiaoxiaohang** [moonheart/mementomori-helper#3]
我设定为p1,p2是输出,最后在p3的数值自动停止.在第271次打磨的时候耐力值是到23093,达到耐力设定值22000以上,但没有停止打磨
<img width="316" alt="屏幕截图 2023-09-03 110437" src="https://github.com/moonheart/mementomori-helper/assets/69664925/aeea6d4a-406a-494c-9bf8-086abe0da439">
<img width="360" alt="屏幕截图 2023-09-03 110727" src="https://github.com/moonheart/mementomori-helper/assets/69664925/fc86f92f-0c24-434e-b89a-c92af26a9a1d">
<img width="412" alt="屏幕截图 2023-09-03 110505" src="https://github.com/moonheart/mementomori-helper/assets/69664925/4e403bdf-e4ab-4e34-8dd5-9f4e6a59c240">

**Comment by moonheart** [comment]
输出日志的时候字段写错了，耐力输出的是战技的值，晚点我改一下

**Comment by jiaoxiaohang** [comment]
懂了
