### ISSUE TITLE
时空洞窟报错

### ISSUE THREAD

**Issue by jiaoxiaohang** [moonheart/mementomori-helper#4]
当前第 2层，坐标 0,4，状态 Done, [DungeonBattleGridTypeBattleNormal] 敌人战斗力 0
伺服器發生錯誤。
{"ErrorCode":1,"Message":"","ErrorHandlingType":0,"ErrorMessageId":0,"MessageParams":null}
MementoMori.Exceptions.ApiErrorException: 伺服器發生錯誤。 at MementoMori.MementoMoriFuncs.GetResponse[TReq,TResp](TReq req) in D:\Downloads\mementomori-helper\mementomori-helper-master\MementoMori\MementoMoriFuncs.cs:line 625 at MementoMori.MementoMoriFuncs.AutoDungeonBattle(Action`1 log) in D:\Downloads\mementomori-helper\mementomori-helper-master\MementoMori\MementoMoriFuncs.cs:line 386 at MementoMori.MementoMoriFuncs.<AutoDungeonBattle>b__107_0(Action`1 log, CancellationToken token) in D:\Downloads\mementomori-helper\mementomori-helper-master\MementoMori\MementoMoriFuncs.Ops.cs:line 752 at MementoMori.MementoMoriFuncs.<ExecuteQuickAction>b__90_0() in D:\Downloads\mementomori-helper\mementomori-helper-master\MementoMori\MementoMoriFuncs.Ops.cs:line 138

<img width="1277" alt="屏幕截图 2023-09-12 120840" src="https://github.com/moonheart/mementomori-helper/assets/69664925/4827facd-67e7-4125-a92a-bc131e9d5df4">

**Comment by moonheart** [comment]
把请求的 GuestMBId 找到，可以在报错的日志里看到，比如这个日志里的 ID 就是 58 `{"DungeonGridGuid":"guid","GuestMBId":58,"CurrentTermId":7}`

然后在游戏里点击 增援，看看这个 ID 58 的角色在游戏里面的角色选择列表有没有。

ID对应的角色可以在这里查 https://www.moonheartmoon.com/mementomori-masterbook/?lang=ZhTw&mb=CharacterMB

**Comment by jiaoxiaohang** [comment]
好,下次洞窟我注意下,这次洞窟打完了
