### ISSUE TITLE
账号满足巅峰竞技场条件，但不能使用自动战斗

### ISSUE THREAD

**Issue by sacredcodex** [moonheart/mementomori-helper#54]
返回内容：尚未滿足巔峰競技的參賽條件
但没有额外报错信息

**Comment by moonheart** [comment]
https://github.com/moonheart/mementomori-helper/releases/tag/dev

请尝试下测试版，看是否还存在此问题

**Comment by sacredcodex** [comment]
还是不行

**Comment by sacredcodex** [comment]
[1.8.7](https://github.com/moonheart/mementomori-helper/releases/tag/v1.8.7)已解决
