### ISSUE TITLE
on new version the league legends dosen't work

### ISSUE THREAD

**Issue by SolovastruAndrei** [moonheart/mementomori-helper#55]
on new version it says that i dont meet requirments on legend league....please check...if i enter the game i can do it fine
edit: on 1.8.5 it still works, asked a few friends they have same problem on 1.8.6 but works on 1.8.5

**Comment by SolovastruAndrei** [comment]
![image](https://github.com/moonheart/mementomori-helper/assets/91962171/236b8d03-1d69-4919-a5a6-784ded0f1e3f)

**Comment by sacredcodex** [comment]
The developer @moonheart has tried to fix this.

You can try [this](https://github.com/moonheart/mementomori-helper/releases/tag/dev) version, from #54 .
