### ISSUE TITLE
幻影神殿報酬計算 BUG

### ISSUE THREAD

**Issue by hoshinomichi999** [moonheart/mementomori-helper#57]
幻影神殿在計算報酬時，每次都沒有計算到首次加倍的情況
但是在活動的幻影神殿沒有這種情況 (參考 **吉薇艾爾** 活動: **暮星神殿季**)

提供比較特別的解決方案:
由於首次加倍的獎勵大概都是兩倍多一點，但神殿獎勵的最難關與第二難關獎勵差都明顯不到兩倍
(即使星數差很多顆也是這樣，不過沒有詳細驗證)但與第三難關就會差超過兩倍多了
故可以...
1.捨棄原本的計算加倍方式，改用直接本地計算額外的首次加權*2
2.捨棄用計算的，使用是屬於第幾難關的方式來決定

由於以上方法沒有詳細驗證，如果能找到並修正原本的BUG則用原本的方法即可

--------------------------------------------
上述描述可能造成混淆
在此舉例神殿獎勵與難度的關係:
最難關 獎勵 5x 加倍 +6x
二難關 獎勵 3x 加倍 +3.5x
三難關 獎勵 2x 加倍 +2.2x
最難關與二難關難度相連，所以二難關加倍後的收益>最難關
二難關與三難關難度相連，所以二難關加倍後的收益>最難關
最難關與三難關難度有間隔，所以三難關加倍後的收益<最難關

**Comment by moonheart** [comment]
@hoshinomichi999 晚点我看一下这个问题，可能是漏掉了非活动状态的计算
