### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by jiaoxiaohang** [moonheart/mementomori-helper#6]
<img width="722" alt="屏幕截图 2023-09-17 123108" src="https://github.com/moonheart/mementomori-helper/assets/69664925/80a4f8ff-5891-45fb-be85-97a38ec7a7b4">

**Comment by moonheart** [comment]
是最新版吗

**Comment by jiaoxiaohang** [comment]
> 是最新版吗

对,刚下载的

**Comment by moonheart** [comment]
https://github.com/moonheart/mementomori-helper/actions/runs/6211623058 等这个CI跑完 然后去 Release里下载最新版, 跑完大概需要6分钟

**Comment by jiaoxiaohang** [comment]
可以使用了
