### ISSUE TITLE
On use Use Normal Items feature do not use witch letters and witch's shard(R and SR)

### ISSUE THREAD

**Issue by SolovastruAndrei** [moonheart/mementomori-helper#62]
**Is your feature request related to a problem? Please describe.**
yes, on my high end accounts I have all normal heroes to 5 stars at least I would love not to use witch's letter R/SR and witch shard in case they add limited heroes to the normal pull it's a waste and I can't use the feature just for that....and I would like to use all the rest....gold/red/xp/keys etc

**Describe the solution you'd like**
Either add a different button that dosent use those....or just remove them from use normal items

**Describe alternatives you've considered**
A different button or a list from which you can chose what items to use on auto

**Additional context**
![image](https://github.com/moonheart/mementomori-helper/assets/91962171/1aec4543-411d-4560-825e-f368860963ef)

![image](https://github.com/moonheart/mementomori-helper/assets/91962171/bba6c47e-a6d9-478d-ae11-c0900ae4733d)

**Comment by hoshinomichi999** [comment]
My solution in the current version is downloading another mementomori-helper, then setting different config respectively.
![未命名](https://github.com/moonheart/mementomori-helper/assets/157197972/ae8c3e63-b53a-4ec6-9060-7abb425d1614)

**Comment by moonheart** [comment]
In options, set Box auto use items, does this meets your requirements?

![image](https://github.com/moonheart/mementomori-helper/assets/15916990/39e45ef1-fe5c-4fb1-be6f-b078aa567093)

**Comment by SolovastruAndrei** [comment]
yes thank you
