### ISSUE TITLE
安卓端APP下载安装后打不开，一直在显示初始化

### ISSUE THREAD

**Issue by Hydragonlight** [moonheart/mementomori-helper#63]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hoshinomichi999** [comment]
能截圖嗎?

**Comment by Hydragonlight** [comment]
![5fbc5a0253e874f285e9bb7c11fed779](https://github.com/moonheart/mementomori-helper/assets/164542575/ea8dc5d0-fb53-4226-9e65-d6e4af8a07ea)

**Comment by Hydragonlight** [comment]
大概是卡在这个界面，过了十分钟依旧还是这个界面。麻烦大佬了。

**Comment by moonheart** [comment]
已在最新版修复，请测试一下

**Comment by Hydragonlight** [comment]
感谢大佬，可以使用了，非常感谢。
