### ISSUE TITLE
日常任务奖励

### ISSUE THREAD

**Issue by jiaoxiaohang** [moonheart/mementomori-helper#7]
{"ErrorCode":352000,"Message":"","ErrorHandlingType":0,"ErrorMessageId":0,"MessageParams":null}
{"TargetMissionIdList":[531,538,534,533,536,535,539,537,532,1134]}
尚未解鎖的任務。
https://prd1-ap2-api.mememori-boi.com/api/mission/rewardMission
MementoMori.Exceptions.ApiErrorException: 尚未解鎖的任務。 at MementoMori.MementoNetworkManager.GetResponse[TReq,TResp](TReq req, Action`1 log, Action`1 userData) in D:\Downloads\mementomori-helper\mementomori-helper-master\MementoMori\MementoNetworkManager.cs:line 220 at MementoMori.MementoMoriFuncs.GetResponse[TReq,TResp](TReq req) in D:\Downloads\mementomori-helper\mementomori-helper-master\MementoMori\MementoMoriFuncs.cs:line 464 at MementoMori.MementoMoriFuncs.<CompleteMissions>b__114_0(Action`1 log, CancellationToken token) in D:\Downloads\mementomori-helper\mementomori-helper-master\MementoMori\MementoMoriFuncs.Ops.cs:line 1103 at MementoMori.MementoMoriFuncs.<ExecuteQuickAction>b__80_0() in D:\Downloads\mementomori-helper\mementomori-helper-master\MementoMori\MementoMoriFuncs.Ops.cs:line 135

**Comment by moonheart** [comment]
试试新版

**Comment by moonheart** [comment]
此问题应该已被修复， 如果还有问题请继续反馈
