### ISSUE TITLE
希望加入有限次数的时空洞窟复活选项

### ISSUE THREAD

**Issue by TobyLi223** [moonheart/mementomori-helper#76]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by moonheart** [comment]
在设置中选择自动吃苹果的数量

**Comment by hoshinomichi999** [comment]
這邊可以設定，沒問題的話可以關閉議題了
![image](https://github.com/moonheart/mementomori-helper/assets/157197972/88b38f96-2c4e-4eea-9453-528cf06ef071)
