### ISSUE TITLE
Fail to update 

### ISSUE THREAD

**Issue by Bob719-afk** [moonheart/mementomori-helper#77]
**Describe the bug**
Never gets past Updating local raid enemy MB

**To Reproduce**
1. Load app

**Expected behavior**
Finish updating

**Comment by Bob719-afk** [comment]
Trying to load Current version of helper. Sry forgot to add that.

**Comment by moonheart** [comment]
@Bob719-afk localraidenemymb is the largest one, please make sure your network connection is good
