### ISSUE TITLE
我设置了自动竞技场战斗，但是似乎没作用

### ISSUE THREAD

**Issue by Yixizi** [moonheart/mementomori-helper#80]
我修改自动任务配置时间，在亚服和国际服都尝试在电脑上挂着，但是并没有给我自动战斗，无论脚本是否在凹图，退出登入刷新我都试过，但似乎都没有奏效，暂时我没有关注其他自动任务
  另外，我想知道如果自动战斗完后如果还剩次数，之后又被打下，是否还会自动战斗

**Comment by hoshinomichi999** [comment]
這邊有設定嗎?
![image](https://github.com/moonheart/mementomori-helper/assets/157197972/b6854d44-6963-4074-8240-a4c40c9aa547)

**Comment by Yixizi** [comment]
> 這邊有設定嗎?
> ![image](https://github.com/moonheart/mementomori-helper/assets/157197972/b6854d44-6963-4074-8240-a4c40c9aa547)
> 

我发现问题了，我一直关注设置竞技场时间问题，但是一直没注意到第一个开关

**Comment by moonheart** [comment]
> 我修改自动任务配置时间，在亚服和国际服都尝试在电脑上挂着，但是并没有给我自动战斗，无论脚本是否在凹图，退出登入刷新我都试过，但似乎都没有奏效，暂时我没有关注其他自动任务 另外，我想知道如果自动战斗完后如果还剩次数，之后又被打下，是否还会自动战斗

自动战斗会用完所有次数
