### ISSUE TITLE
增加在祈愿之泉根据钻石的总期望值来自动刷新并派遣任务的功能，可能的话也加入其他类型的奖励（其他类型或许不必按照期望值计算）

### ISSUE THREAD

**Issue by ghost** [moonheart/mementomori-helper#81]
https://wikiwiki.jp/mememori/%E7%A5%88%E3%82%8A%E3%81%AE%E6%B3%89
根据这个网站声称的统计，每个任务能钻石的期望值是 Rank 3 = 3.0，Rank 4 = 5.6，Rank 5 = 7.7，Rank 6 = 9.7，Rank 7 = 10.8，Rank 8 = 12.7

流程
获得祈愿之泉的等级以确定单个任务钻石的期望值（自动检测或由使用者输入）
总钻石期望值=非钻石任务数x对应等级钻石的期望值
如存在钻石任务则锁定或直接派遣
如果总钻石期望值＞刷新费用20 则进行刷新（这里应当设法确保总花费不超过初始期望值，并且只在单次花费也低于当下期望值时才进行刷新：或许除了单次检测外再保留初始的总期望，初始总期望值的余量=初始总期望值-花费20，刷新同时检测初始总期望值的余量与当下期望值）
  如存在钻石任务则锁定或直接派遣
直到初始钻石期望值余量＜刷新费用20 OR 本次钻石总期望值＜刷新费用20 则派遣全部（剩余）任务
如果钻石任务只用来刷新任务到优先类型而弥补钻石消耗，设置余量避免刷新过多而超过上限；如果考虑偶尔的好运或赚钻石的话，或许设置一个比刷新费用20更大的数字。我的等级很低，于是一直都是前者，而没考虑过要赚钻石，但看了上面网站的那张表，在中后期确实应该考虑一下后者

在多倍活动时也按照多倍计算

钻石估计大家都会优先考虑而且刷新费用也是钻石，任务的钻石期望值在这里比较好算

如果能加入这个功能就已经很好用了，再继续的话或许是：
能够在全自动的流程中选择锁定或直接派遣优先奖励类型（就不只是钻石了，或许也能与上面的同时使用。如优先钻石与符石，同样按照上面的流程但符石也与钻石任务一样锁定或直接派遣，刷新时计算的剩余任务数也一样排除符石）
 或自选要排除的奖励类型并拥有可选的刷新次数上限
  或按照排除类型的任务总数量进行刷新（如，金币与碎片任务总数＞2则进行一次刷新。这个功能或许也能与上面的一起使用）
最后派遣全部（剩余）任务实现全自动，告别手动祈愿之泉的时代！！

还有个不知能否实现的功能：如果检测到已拥有的角色阶级不满足优先奖励类型的任务要求（要求ssr，但只有sr），那么也将其算入非优先任务类型中（或许能够以检查自动派遣是否成功来测定）

由于app显示新建的账号数据不存在还没实际用过，不知游击是否使用拥有最高阶级的3个同属性角色，因为这样奖励会有3个

**Comment by moonheart** [comment]
> 由于app显示新建的账号数据不存在还没实际用过，不知游击是否使用拥有最高阶级的3个同属性角色，因为这样奖励会有3个

游击是自动使用最高稀有度的

**Comment by lIlIIlIllI** [comment]
> > 由于app显示新建的账号数据不存在还没实际用过，不知游击是否使用拥有最高阶级的3个同属性角色，因为这样奖励会有3个
> 
> 游击是自动使用最高稀有度的

这会有些损失，还是按照上面这个网站，他表示同属性3位有3个奖励、同属性2位有2个奖励、全不同属性3位有1个奖励
