### ISSUE TITLE
网页“选项”中“召唤”与“商城”的个别项目名称都出现重复

### ISSUE THREAD

**Issue by ghost** [moonheart/mementomori-helper#84]
![屏幕截图 2024-06-24 033843](https://github.com/moonheart/mementomori-helper/assets/55037215/cd2b79f0-010c-4e57-86cb-80fd62805731)

召唤：
两个白金召唤卷不知是什么情况，没敢选。有两种编号不同的白金召唤券？

商城：
两个“用公会币购买符石兑换券”对应“符石兌換券×20”/“符石兌換券×30”，预计其他类似项目的描述都是这样。也不算是什么问题，只是描述不清晰

**Comment by moonheart** [comment]
已在 v1.12.0 中解决
