### ISSUE TITLE
安卓没办法找到PlayerPrefs生成的xml

### ISSUE THREAD

**Issue by JasonXuDeveloper** [moonheart/mementomori-helper#9]
在安卓上，`data/data/jp.mementomori.android`内只有`cache`跟`files`目录，`cache`里是shader的缓存，files里是assetbundles跟配置表之类的。
确实有登录游戏，且账号信息被缓存了，重启也能直接进，不需要再登录一次

**Comment by moonheart** [comment]
你找错地方了，你说的是 `/sdcard/Android/data/jp.boi.mementomori.android/`；应该是 `/data/data/jp.boi.mementomori.android/`， 这个目录只有 root 权限才能看到。

**Comment by JasonXuDeveloper** [comment]
有开root的，但这个是云手机，不知道怎么开开发者模式，我琢磨下

**Comment by moonheart** [comment]
用 MT管理器看看？https://mt2.cn/ ，如果确实没有的话，那可能是这个云手机的系统做了什么修改

**Comment by JasonXuDeveloper** [comment]
我用云手机想办法ssh到我电脑上然后cat文件吧，现在xml文件在云手机的clipboard上，多谢了

**Comment by moonheart** [comment]
> 找到了，多谢，一定要给这个xml拷贝到webui工程里吗，可不可以只配置clientKey和userId

可以的，文档上写了第二种方式，只需要 UserId 和 ClientKey

**Comment by JasonXuDeveloper** [comment]
可以登录了，多谢

**Comment by JasonXuDeveloper** [comment]
这个clientKey是一直有效的吧，不会像token一样需要定时获取的吧？

**Comment by moonheart** [comment]
一直有效的

**Comment by JasonXuDeveloper** [comment]
好的，多谢
