### ISSUE TITLE
Fraudulent request bug

### ISSUE THREAD

**Issue by Bob719-afk** [moonheart/mementomori-helper#91]
Updated to new version and get Fraudulent account Everytime I try to link my account.

**Comment by moonheart** [comment]
Please try again now, token has now updated.

**Comment by Bob719-afk** [comment]
Nope still fraudulent request do I need to reinstall?

**Comment by moonheart** [comment]
Please try again, there is a cache issue and now it's resolved

**Comment by Bob719-afk** [comment]
Ok it finally let me sign in. Ty for speedy response. Cheers
