### ISSUE TITLE
"This request is fraudulent" when add new account after game maintenance update

### ISSUE THREAD

**Issue by kritpunpreuk** [moonheart/mementomori-helper#98]
**Describe the bug**
when add new account and login got response "This request is fraudulent."

**To Reproduce**
1. Go to 'Add acccount'
2. Enter account id and password
3. Press confirm
4. See error "This request is fraudulent"

**Expected behavior**
Add account completed.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Version 128.0.6613.86

**Comment by moonheart** [comment]
try again,should be fixed now

**Comment by kritpunpreuk** [comment]
Thank you, It's worked.
