### ISSUE TITLE
幻影神殿功能需要能自己创建房间打

### ISSUE THREAD

**Issue by kbCalem** [moonheart/mementomori-helper#99]
战斗力可以碾压神殿，但是神殿不能自己创建房间，等up时间到了自己又不能挂着脚本
所以需要一个自己创建房间自己打的功能（

**Comment by moonheart** [comment]
@kbCalem 设置里可以开启创建房间的功能

**Comment by kbCalem** [comment]
我勒个，随机加入旁边的按钮我以为是开启/关闭，原来是随机加入和创建房间吗
